### ISSUE TITLE
有试过，Python 3.6.8，我这里调用脚本后，不能更新域名 txt 记录

### ISSUE THREAD

**Issue by wangyouworld** [al-one/certbot-auth-dnspod#4]
日志中，记录的部分：
To fix these errors, please make sure that your domain name was entered correctly and the DNS A/AAAA record(s) for that 
domain contain(s) the right IP address.
2021-01-21 18:35:02,843:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/opt/eff.org/certbot/venv/lib64/python3.6/site-packages/certbot/_internal/auth_handler.py", line 91, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/opt/eff.org/certbot/venv/lib64/python3.6/site-packages/certbot/_internal/auth_handler.py", line 180, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.

1、Python 3.6.8
2、SSL，使用的是泛解析（多个不同名称的域名使用同一证书，以前是可以的）
3、certbot-auth-dnspod.sh 脚本文件中，我将原来的 python，改为了 python3。
dsnpod 的 token是正确的，我专门使用官方的接口示例调试过。

谢谢！

**Comment by wangyouworld** [comment]
另外，使用 clean 参数时，报 /tmp/CERTBOT_test.com/RECORD_ID_N69sdnzlGuEJ6GJn6TZzZs8M 不存在。
不使用时，也生成类似文件，但里面存的是：Token 验证失败。

使用设置的 token ，调用官方接口，证明 token是正确的。

不解。

**Comment by wangyouworld** [comment]
问题找到了，token换行符问题。
我把 token放在 /etc/dnspod_token 里了，在调试时，看到有换行符（不解），之后将 token 写到 certbot-auth-dnspod.sh API_TOKEN=""里，再执行时，竟可以了。

不知道.sh 文件中，这样修改是否可以。

$(cat /etc/dnspod_token | -head -n 1)

再次续期时看看情况。

再次感谢作者！
